export const PageHero = {
  baseStyle: {
    outerWrapper: {
      position: 'relative',
    },
    containerStyles: {
      position: 'relative',
      display: 'grid',
      gridTemplateColumns: '1fr',
      mt: 0,
      minHeight: [400, 500],
      color: 'primary',
      bg: 'primary',
      //   background: `radial-gradient(circle, #477846 0%, #355f34 60%, #2a4b29 100%)`, // ! Replace this with custom color and uncomment to add a gradient effect with brand color
    },
    innerContainerStyles: {
      position: 'relative',
      height: ['auto', '90vh', 550],
    },
    image: {
      objectFit: 'cover',
      height: '100%',
      width: '100%',
    },
    overlay: {
      pos: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
      p: 1,
      px: 0,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'flex-end',
    },
    heading1: {
      as: 'h1',
      color: 'white',
      fontSize: ['lg', '4xl', '4xl', '4xl', '4xl', '5xl'],
      textAlign: 'center',
      width: '100%',
      py: [2, 2],
      px: [4, 12, 12],
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 3,
      maxWidth: '5xl',
      mx: 'auto',
    },
    heading2: {
      as: 'h2',
      color: 'secondary',
      fontSize: ['2xl', '2xl', 'xl', 'xl', '', 'xl'],
      textAlign: 'center',
      width: '100%',
      py: [2, 2],
      px: [14, 12, 12],
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 3,
      maxWidth: '5xl',
      mx: 'auto',
    },
  },
  variants: {},
};
